version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:current

jobs:
  setup-qemu:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Enable QEMU for multi-arch
          command: |
            docker run --rm --privileged tonistiigi/binfmt --install all

  build-and-push:
    executor: docker-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Set up Docker Buildx
          command: |
            docker buildx create --use
            docker buildx inspect --bootstrap
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build and push multi-arch Docker image
          command: |
            docker buildx build --platform linux/amd64,linux/arm64 -t sharinpix/docker-heroku:latest --push .

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup-qemu
      - build-and-push:
          requires:
            - setup-qemu
